# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n8RLTXUNFzLyhZKa0ekAQCxuU6YoCb6Y
"""

class Persona:
  def __init__(self, nombre, nif, fechaNac):
    self.nombre = nombre
    self.nif = nif
    self.fechaNac = fechaNac

  def getNombre(self):
    return self.nombre

  def getNif(self):
    return self.nif 

  def getfechaNac(self):
    return self.fechaNac

class Jugador(Persona):
  def __init__(self, nombre, nif, fechaNac, numFed):
    self.numFed = numFed

    def getnumDef(self):
      return self.getNombre + self.numFed + self.nif()